
name: test

on:
  push:
    branches: [ master, DO1-pylint_config ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install setuptools
        pip3 install Flask
        pip3 install Flask-SocketIO
        pip3 install docopt
        pip3 install eventlet
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint *.py
