# This is a basic workflow to help you get started with Actions

name: Unittest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Install dependencies
      - name: Installation des librairies
        run: |
          sudo apt-get install -y python3-flask
          sudo apt-get install -y python3-flask-socketio
          sudo apt-get install -y python3-eventlet
          sudo apt-get install -y python3-docopt
          sudo apt-get install -y python3-setuptools
          sudo pip install python3-socketio

      # Runs a set of commands using the runners shell
      - name: Test de la base de données
        run: |
          python3 -m unittest tests/testBdd.py -v
      - name: Test du code Client
        run: |
          python3 -m unittest tests/testClient.py -v
      - name: Test du code Serveur 
        run: |
          python3 -m unittest tests/testServer.py -v
  
